name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  deploy-firebase:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to a branch
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@master
      - name: Install dependencies
        run: npm install
      - name: Build the application
        run: npm run build
      - name: Deploy with Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FirebaseDeploy }}
